name: tuldokator
description: "A lightweight Flutter widget for customizable dot indicators, commonly used to show the current page in a PageView."
version: 0.0.1
repository: https://github.com/johnnydevvcodes/tuldokator
issue_tracker: https://github.com/johnnydevvcodes/tuldokator/issues

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: